### ISSUE TITLE
Argument with name 'version' is not working

### ISSUE THREAD

**Issue by arulned** [sywac/sywac#12]
If we use '--version' as an argument instead of the program version, the value is null. My app would look like:
`$ my-command list-configuration --version=2`
My command is always getting the version argument as `null`

**Comment by arulned** [comment]
its a bug in my code

**Comment by nexdrew** [comment]
@arulned Hi 👋

Glad you were able to solve your problem. Please let me know if you have any questions or run into any other issues. I'd be glad to help out.

Thanks for using sywac!

**Comment by arulned** [comment]
@nexdrew, Is it possible to use --version as both argument to a command and to display the version of the program based on the registration? Right now sywac.version('--version).string('--version <v>') does not work because they are not distinguishable in the options array where they end up.

**Comment by nexdrew** [comment]
@arulned Unfortunately you cannot reuse the same flag for different arguments when one of them is a "global" (top-level) option. In the case of `sywac.version('--version').string('--version <v>')` both options are "global" and the `.version()` one wins because sywac gives precedence to short-circuiting options like `.version()` and `.help()` over others.

If you were using commands, then you could reuse the same flag for different purposes across commands, but IMO this can cause confusion for your CLI users. Here's an example:

```js
// cmd.js
require('sywac')
  .command('one', {
    setup: sywac => sywac.boolean('--version'),
    run: argv => console.log('one:', argv)
  })
  .command('two', {
    setup: sywac => sywac.string('--version <v>'),
    run: argv => console.log('two:', argv)
  })
  .parseAndExit()
```

```console
$ node cmd.js one --version x
one: { version: true, _: [ 'x' ] }

$ node cmd.js two --version x
two: { version: 'x', _: [] }
```

I would recommend using a different flag for the special `.version()` option, perhaps something like this:

```js
// v2.js
require('sywac')
  .string('-v, --version <version>', { desc: 'Specify a version' })
  .help('-h, --help', { desc: 'Print this help text and exit' })
  .version('-V, --ver', { desc: 'Print the program version and exit' })
  .outputSettings({ maxWidth: 90 })
  .parseAndExit()
  .then(argv => console.log(argv))
```

```console
$ node v2.js -h
Usage: v2 [options]

Options:
  -v, --version <version>  Specify a version                                      [string]
  -h, --help               Print this help text and exit        [commands: help] [boolean]
  -V, --ver                Print the program version and exit    [commands: ver] [boolean]

$ node v2.js --version 1.2.3
{ _: [],
  v: '1.2.3',
  version: '1.2.3',
  h: false,
  help: false,
  V: false,
  ver: false }

$ node v2.js -V
1.0.0
```

Also note that sywac supports _positional arguments_, so you could potentially do something like this as well:

```js
// v3.js
require('sywac')
  .positional('[version]', {
    params: [{
      aliases: 'ver',
      desc: 'Specify a version',
      type: 'string'
    }]
  })
  .version('-v, --version')
  .help('-h, --help')
  .outputSettings({ maxWidth: 75 })
  .parseAndExit()
  .then(argv => console.log(argv))
```

which would display `[version]` as the argument in help text but would apply the value to `argv.ver`.

```console
$ node v3.js --help
Usage: v3 [version] [options]

Arguments:
  [version]  Specify a version                                     [string]

Options:
  -v, --version  Show version number          [commands: version] [boolean]
  -h, --help     Show help                       [commands: help] [boolean]

$ node v3.js 1.2.3
{ _: [],
  ver: '1.2.3',
  v: false,
  version: false,
  h: false,
  help: false }

$ node v3.js --version
1.0.0
```

I hope this helps! Let me know if you have any more questions.

**Comment by arulned** [comment]
@nexdrew Thank you. I like your `--ver` option. 
Also since the documentation is in progress, I would like to know how to move my commands in separate files.
I have around 20 commands of the format:
sywac.command('command1',{
    setup: sywac => {
      sywac.number("--arg1 <id>", {
          required: false
      });
  },
  run: options => {
      new Command1Class(options).methodReturningPromise().then(result=>{
          // do something
    });
  }
});
`
I want 5 commands in each file and load these commands in the mail executable. I went through [this](http://sywac.io/docs/sync-config.html#command) and [this](http://sywac.io/docs/sync-config.html#commandDirectory) but could not succeed. Could you point me to an example where this is used?

**Comment by nexdrew** [comment]
@arulned The idea behind command modules is:

- Each file represents a single module
- Each module represents a single command
- The command is defined by what the module exports
- The module should export the same type of object you would pass to the `.command()` method (as the 2nd argument), with the addition of a `flags` property (that you would normally pass as the 1st argument) which defines the command name and any positional args for the command.

Take a look at [these command modules used in sywac tests](https://github.com/sywac/sywac/tree/2b4fe0f0c012ebce92a801db01ab2d0a1052d61f/test/fixture/cmds) for examples.

**Note** that a command module can just be a function, as below, but exporting a function precludes the ability to define metadata (e.g. `desc`, positional args, `setup`, etc) for the command:

```js
// commands/wait.js
module.exports = async function () {
  console.log('waiting for one second')
  await new Promise(resolve => {
    setTimeout(resolve, 1000)
  })
  console.log('done waiting')
}
```

When exporting a function, it will be used as the command's `run` handler, which can be asynchronous, and the name of the command will be the file name (without extension).

**Also note** that a command module can be an instance of a class, like so:

```js
// commands/sleep.js
class SleepCommand {
  constructor () {
    this.flags = 'sleep [ms=1000]'
    this.desc = 'Sleep for a certain amount of time'
    this.params = [{
      type: 'number',
      desc: 'The number of milliseconds to sleep',
      coerce: val => isNaN(val) ? 0 : Math.max(0, val)
    }]
    this.setup = this.setup.bind(this)
    this.run = this.run.bind(this)
  }

  setup (sywac) {
    console.log('sleep setup')
  }

  async run (argv) {
    console.log(`sleeping for ${argv.ms} ms`)
    await new Promise(resolve => {
      setTimeout(resolve, argv.ms)
    })
    console.log('done sleeping')
  }
}

module.exports = new SleepCommand()
```

Once you have your command modules/files defined, you can put them all in the same directory and then load them all at once using `.commandDirectory()`, like so:

```js
// cli.js
#!/usr/bin/env node
'use strict'

const sywac = require('sywac')

sywac
  .commandDirectory('commands')
  .showHelpByDefault()
  .help('-h, --help')
  .version('-v, --version')

module.exports = sywac

if (require.main === module) {
  sywac.parseAndExit().then(() => console.log('success!'))
}
```

Perhaps I'll create a small repo with examples like these for reference. In the meantime, let me know if this gets you on your feet.

**Comment by arulned** [comment]
@nexdrew I know you support `command subcommand <args>` from the docs.
Do you also support the format:
`command <argument> subcommand <arguments>`

**Comment by nexdrew** [comment]
@arulned No, sywac does not support positional arguments before subcommands. I don't think I've ever seen a CLI that works that way.

Note that sywac _does_ allow users of your CLI to specify "global" options/flags before subcommands, just not positional arguments. Here's an example:

```js
// cli.js
const two = {
  flags: 'two <arg>',
  setup: sywac => sywac.boolean('-2'),
  run: argv => console.log('subcommand:', argv)
}

const one = {
  flags: 'one',
  setup: sywac => sywac.boolean('-1').command(two)
}

require('sywac')
  .boolean('-g, --global')
  .command(one)
  .parseAndExit()
```

```console
$ node cli.js one two x
subcommand: { '1': false, '2': false, _: [], g: false, global: false, arg: 'x' }

$ node cli.js one two x -g -1 -2
subcommand: { '1': true, '2': true, _: [], g: true, global: true, arg: 'x' }

$ node cli.js one -g -1 two -2 x
subcommand: { '1': true, '2': true, _: [], g: true, global: true, arg: 'x' }

$ node cli.js -g one -1 two x
subcommand: { '1': true, '2': false, _: [], g: true, global: true, arg: 'x' }
```

Note the placement of the `-g` and `-1` flags before or after the `two` subcommand.

**Comment by arulned** [comment]
@nexdrew The scenario for me is like this:
I have an entity which i need to update by adding elements to its attribute which is an array. Lets say i have an object person like so:
```
{
  "id":102,
  "name":"John",
  "vehicles":["honda","bmw"]
}
```
The command looks something like:
`my-command update-person 102 add-vehicle toyota`
This is what I am looking for.

**Comment by nexdrew** [comment]
In that case, I would recommend one of the following:

1. Define person id as a flag

    ```
    my-command update-person --id 102 add-vehicle toyota
    ```

2. Define the subcommand as a flag

    ```
    my-command update-person 102 --add-vehice toyota
    ```

3. Use multiple positional args for the update-person command and treat the 2nd one as a pseudo-subcommand (do a string check and call your own function)
