### ISSUE TITLE
Sywac -support for position parameters?

### ISSUE THREAD

**Issue by davidkjackson54** [sywac/sywac#27]
I have a need to be able to support positional parameters for example:
cli.js jobs status --jname

where jobs and status are both positional parameters and jname is a required subparm.
I know yargs can handle this but I haven't been able to find any documentation or examples on how to accomplish this in sywac. I also need to have the help auto generated for this. So a user could enter
cli.js --help
cli.js jobs --help
cli,js jobs status --help

Are there any samples of how i can accomplish this available? i have looked in the doc at sywac.io but not found anything.

**Comment by nexdrew** [comment]
Yes, sywac supports this. I would attempt to give you a working example, but I am currently AFK.

In the meantime take a look at the docs for the `.positional()` method: http://sywac.io/docs/sync-config.html#positional

**Comment by davidkjackson54** [comment]
Thanks but I had already reviewed that positional parm but couldn't fathom out from reading it how to handle multiple positional parms like in my example above and the  link to the 'see more and examples..' doesn't exist.  [](http://sywac.io/docs/positional-type.html).  if you get chance to knock up a working example it would be appreciated.

**Comment by nexdrew** [comment]
I think we have our terminology mixed up. What you're calling _positional parameters_ are what sywac calls _commands_. Commands are actions executed by name/alias. Positional arguments are variables given without a preceding flag.

I think you want to use commands, but for sake of comparison/completeness, I'll provide examples of both below.

(Note that the use of `.style(require('sywac-style-basic'))` in these examples is not necessary, but it adds a nice bit of color to the help text that you can see if you run it yourself.)

### Example of Positional Arguments

Based on what you describe above, here's a working example of **positional arguments**:

```js
#!/usr/bin/env node
require('sywac')
  .positional('<jobs> <status>', {
    paramsDesc: [
      'Some description for jobs',
      'Some description for status'
    ]
  })
  .string('-j, --jname <name>', {
    desc: 'The name of the job',
    required: true,
    group: 'Required Options:'
  })
  .help('-h, --help', {
    implicitCommand: false
  })
  .style(require('sywac-style-basic'))
  .outputSettings({ maxWidth: 62 })
  .parseAndExit()
  .then(argv => {
    console.log('jobs param:', argv.jobs)
    console.log('status param:', argv.status)
    console.log('jname flag:', argv.jname)
  })
```

Note that, in this example, the auto-generated help text is the same at each "level":

```console
$ ./issue27p.js --help
Usage: issue27p <jobs> <status> [options]

Arguments:
  <jobs>    Some description for jobs      [required] [string]
  <status>  Some description for status    [required] [string]

Required Options:
  -j, --jname <name>  The name of the job  [required] [string]

Options:
  -h, --help  Show help                              [boolean]
```

```console
$ ./issue27p.js jobs --help
Usage: issue27p <jobs> <status> [options]

Arguments:
  <jobs>    Some description for jobs      [required] [string]
  <status>  Some description for status    [required] [string]

Required Options:
  -j, --jname <name>  The name of the job  [required] [string]

Options:
  -h, --help  Show help                              [boolean]
```

```console
$ ./issue27p.js jobs status --help
Usage: issue27p <jobs> <status> [options]

Arguments:
  <jobs>    Some description for jobs      [required] [string]
  <status>  Some description for status    [required] [string]

Required Options:
  -j, --jname <name>  The name of the job  [required] [string]

Options:
  -h, --help  Show help                              [boolean]
```

```console
$ ./issue27p.js x y -j z
jobs param: x
status param: y
jname flag: z
```

From this you can see that what I gave on the command line were interpreted as variable values, and each variable is thrown into a "global" parsed `argv` object. This is probably not what you want.

### Example of Nested Commands

And here's a working example of **commands**:

(Note that I threw a pseudo `jobs list` command in there for demo purposes.)

(Also note that this example uses a single file for sake of simplicity, but each command or set of commands could go in their own modules/files, which would probably be easier to read/maintain.)

```js
#!/usr/bin/env node
require('sywac')
  .command('jobs', {
    desc: 'Work with jobs',
    setup: sywac => {
      sywac
        .command('list', {
          aliases: '*',
          desc: 'List jobs',
          run: argv => console.log('List jobs')
        })
        .command('status [-j|--jname] <name>', {
          desc: 'Check status of job',
          paramsDesc: ['The name of the job'],
          run: argv => console.log('Check status of job:', argv.jname)
        })
    }
  })
  .showHelpByDefault()
  .help('-h, --help', {
    implicitCommand: false
  })
  .style(require('sywac-style-basic'))
  .outputSettings({ maxWidth: 63 })
  .parseAndExit()
```

In this example, the auto-generated help text is different/contextual to each "level":

```console
$ ./issue27c.js --help
Usage: issue27c <command> [options]

Commands:
  jobs  Work with jobs

Options:
  -h, --help  Show help                               [boolean]
```

```console
$ ./issue27c.js jobs --help
Usage: issue27c jobs <command> <args> [options]

Commands:
  list                        List jobs               [default]
  status [-j|--jname] <name>  Check status of job

Options:
  -h, --help  Show help                               [boolean]
```

```console
$ ./issue27c.js jobs status --help
Usage: issue27c jobs status [-j|--jname] <name> [options]

Arguments:
  [-j|--jname] <name>  The name of the job  [required] [string]

Options:
  -h, --help  Show help                               [boolean]
```

In this example, I made the pseudo `list` command the default by giving it the `'*'` alias, meaning it will run with either `jobs list` or just `jobs`:

```console
$ ./issue27c.js jobs list
List jobs
```

```console
$ ./issue27c.js jobs
List jobs
```

And, finally, to check the status of a job by name, I used a single positional arg called `name` that can be used with or without a preceding `-j` or `--jname` flag:

```console
$ ./issue27c.js jobs status --jname blerg
Check status of job: blerg
```

```console
$ ./issue27c.js jobs status -j blarg
Check status of job: blarg
```

```console
$ ./issue27c.js jobs status blorg
Check status of job: blorg
```

Let me know what further questions you have.

**Comment by davidkjackson54** [comment]
Thanks.
This helps a lot in the clarification.
I had found your code for issue 27 yesterday and that also helped
tremendously.
A working example speaks volumes in clarifying the process. An example such
as this in the doc on nested commands would be beneficial.

I now have a good handle on what I need to do and will go through your code
that you give below in detail.

However, just a comment.
The lack of completed doc really does make it difficult to follow. I
suspect that some folk might be turned off by that.
I have persevered as I quite like sywac and think it could be way better
than commander.

The doc that you have done so far is very good. It is just so frustrating
to a user to read it and it points to a link for more info and you follow
that link only for it to say that doc section is not yet unavailable.
I know writing doc is a pain but it, really would benefit the uptake of
sywac.

**Comment by nexdrew** [comment]
> The lack of completed doc really does make it difficult to follow. I
> suspect that some folk might be turned off by that.

Yeah, I totally understand that. I appreciate your thoughts and welcome any specific ideas you have.

> I have persevered as I quite like sywac and think it could be way better
> than commander.

Thank you. I agree.

> The doc that you have done so far is very good. It is just so frustrating
> to a user to read it and it points to a link for more info and you follow
> that link only for it to say that doc section is not yet unavailable.
> I know writing doc is a pain but it, really would benefit the uptake of
> sywac.

Yes, I understand and agree. Per issue #11, I would greatly appreciate any help I could receive when it comes to documentation. I'll see if I can carve out some time over the next couple weeks to fill in the remaining pages, but I can't guarantee anything. In my experience, most users don't read the docs anyway, but at least it would give me something to point folks to.

Thanks for your feedback!

**Comment by davidkjackson54** [comment]
I should have a working piece of code later today.   I think it will end up
being pretty simple as most of the grunt work is done and will largely be a
repetitive exercise across my commands and subcommands.
I will send you a snippet so you can advise if I have missed anything
obvious.

Once I have it done, I will revisit the doc.

David

**Comment by davidkjackson54** [comment]
Couple of questions:
I have a command with a lot of parameters.
.command('create [-n|--name] <value> [-h|--host] <value> [-u|--user] <value> [-p|--pass] <value>', {

being so long it screws up the help display. The Descriptive text asociated with the command is displayed  1 character at a time  on separate lines.
Is there a way of having this command split in a certain display position such that the help will flow correctly?

Secondly, the manual refers to the ability to enter Examples: 
in the help screen but doesn't explain how.
it states:
The “Examples” make up the fourth section, with its own heading, showing description (if any) and command per given example.
The example isn't code - just a screen image.

**Comment by nexdrew** [comment]
I know it's probably not clear, but you shouldn't put all your options/flags in the command string, only positional args should go there. For standard options that are command-specific, use a `setup` handler to define the options for the command, like so:

```js
.command('create', {
  desc: 'Create something',
  setup: sywac => {
    sywac
      .string('-n, --name <name>', { desc: 'A name' })
      .string('-h, --host <host>', { desc: 'The host' })
      .string('-u, --user <user>', { desc: 'The user' })
      .string('-p, --pass <secret>', { desc: 'Password or passphrase' })
  },
  run: argv => {
    // do something with argv.name, argv.host, argv.user, argv.pass
  }
})
```

**Comment by nexdrew** [comment]
Use the [`.example(example, opts)` method](http://sywac.io/docs/sync-config.html#example) to add CLI examples to your help text, like so:

```js
.example('$0 create -n blerg -h xyz -u chachi -p "super secret"', {
  desc: 'Create blerg on host xyz via user chachi'
})
```

The `$0` part of the example will be replaced with your CLI bin/module name, just like in usage content.

**Comment by davidkjackson54** [comment]
Hi again. 
Reading the doc, I see one single reference to the use of  coerce .  I think it might be something I  need to use to test for the presence of an entered option. If the option was entered, I want to prefix it 
If it wasn't entered (i.e. undefined), I want to set it to '' (null).    Is there any example of coerce  or further doc?

**Comment by nexdrew** [comment]
Currently AFK, but there are a couple examples of using `coerce` in tests here: https://github.com/sywac/sywac/blob/7e7eff1e6d583b75857e19353067c10f51d92437/test/test-parse.js#L220

It supports any synchronous function, on a per-option basis, that should return the value to be used in the parade argv.

**Comment by davidkjackson54** [comment]
One final question that I cannot determine from the doc.
I have a top level command e.g. files , an intermediate command e.g. get and a lower level command 
I then have a second intermediate command 'create'.
It works fine
What I want do is to split up the .command for 'get' into a separate module and the same for 'create' 
and then use .command(require('./getfile'))  and .command(require('./create file'))
in order to keep the code modular and within reasonable size.

However, no matter how I slice and dice this, I have been unable to slice the code without getting errors.
 
module.exports = {
  flags: 'files',
  desc: 'xxxxxxx....xxxx.',
  setup: sywac => {
    sywac
      .command('get', { // intermediate command
        desc: 'Retrieve a file',
        setup: sywac => {
          sywac
              .command('file [-f|--fn] <filename>', {
              desc: xxxxxx',
              paramsDesc: [Filename],
              setup: sywac => {
                sywac
                  .boolean('-b, --binary',
                    { desc: 'Binary mode', defaultValue: 'false' })
                 },
              run: async (parsedArgv, context) => {
                 await new Promise(resolve => {
                // function to execute when command is used
                  var downloadds = require('../controller/files/downloadds')
                  downloadds.init(parsedArgv.dataset, parsedArgv.binary,
                    parsedArgv.extension, parsedArgv.path, parsedArgv.volser)
                })
              } // end run
            }) // end command block
        } // end setup block
      }) // end intermediate get command

      .command('create', { // intermediate command and description
        desc: 'Create a z/OS dataset',
etc etc etc

**Comment by davidkjackson54** [comment]
Any suggestion on how to slice the source code to allow this be be maintained in a more granular fashion?

**Comment by nexdrew** [comment]
Use directories to represent levels of commands, and put the commands at each level inside their own module/file within the appropriate directory.

Here's an example:

Structure:
```
issue27m.js
issue27-cmds/
  files.js
  file-cmds/
    create.js
    get.js
    get-cmds/
      file.js
```

issue27m.js (executable):
```js
#!/usr/bin/env node
require('sywac')
  .commandDirectory('issue27-cmds') // apply all command modules in this relative directory
  .showHelpByDefault()
  .help('-h, --help', {
    group: 'Global Options:',
    implicitCommand: false
  })
  .style(require('sywac-style-basic'))
  .outputSettings({ maxWidth: 57 })
  .parseAndExit()
```

issue27-cmds/files.js:
```js
module.exports = {
  flags: 'files',
  desc: 'Work with files',
  setup: sywac => {
    sywac.commandDirectory('file-cmds')
  }
}
```

issue27-cmds/file-cmds/create.js:
```js
module.exports = {
  flags: 'create',
  desc: 'Create a file',
  run: argv => {
    console.log('create a new file')
  }
}
```

issue27-cmds/file-cmds/get.js:
```js
module.exports = {
  flags: 'get',
  desc: 'Retrieve a file',
  setup: sywac => {
    sywac.commandDirectory('get-cmds')
  }
}
```

issue27-cmds/file-cmds/get-cmds/file.js:
```js
module.exports = {
  flags: 'file [-f|--fn] <name>',
  paramsDesc: 'Name of file',
  setup: sywac => {
    sywac.boolean('-b, --binary', { desc: 'Binary mode' })
  },
  run: async (argv, context) => {
    console.log(`get ${argv.b ? 'binary' : 'text'} file ${argv.name}`)
  }
}
```

Run it:
```console
$ ./issue27m.js
Usage: issue27m <command> [options]

Commands:
  files  Work with files

Global Options:
  -h, --help  Show help                         [boolean]
```

```console
$ ./issue27m.js files
Usage: issue27m files <command> [options]

Commands:
  create  Create a file
  get     Retrieve a file

Global Options:
  -h, --help  Show help                         [boolean]
```

```console
$ ./issue27m.js files create
create a new file
```

```console
$ ./issue27m.js files get
Usage: issue27m files get <command> <args> [options]

Commands:
  file [-f|--fn] <name>

Global Options:
  -h, --help  Show help                         [boolean]
```

```console
$ ./issue27m.js files get file
Usage: issue27m files get file [-f|--fn] <name> [options]

Arguments:
  [-f|--fn] <name>  Name of file      [required] [string]

Options:
  -b, --binary  Binary mode                     [boolean]

Global Options:
  -h, --help  Show help                         [boolean]

Missing required argument: f or fn or name
```

```console
$ ./issue27m.js files get file foo.txt
get text file foo.txt
```

```console
$ ./issue27m.js files get file foo.zip -b
get binary file foo.zip
```

As you can see, using [`.commandDirectory(dir, opts)`](http://sywac.io/docs/sync-config.html#commandDirectory) makes it easy to structure any arbitrary level of nested commands-as-modules.

(Note: When pasting/writing code in an issue, please format it so I can more easily read it. I might have responded sooner if you had taken the time to do this.)

**Comment by davidkjackson54** [comment]
Andrew, great info thanks.That would be good to put in the doc when you get to it. Apologies on the lack of formatting - my bad. sorry.

**Comment by davidkjackson54** [comment]
Andrew, 
One of the commands in my CLI will be to delete a file or a directory. 

In the case of a directory, is there any means in sywac that will allow me to put out a 'Are you sure'  prompt before  proceeding? To which the user must respond.   
Ideally, I want to have a -f parm (for force) that if true will not put out that prompt.

**Comment by nexdrew** [comment]
There is no api method in sywac that provides user prompts out-of-the-box.

However, since sywac supports `async` run functions for commands, you could do a conditional `await` on a Promise that prompts the user and waits for a response via stdin, perhaps using something like inquirer or promzard.

If I have satisfactorily answered your question about the original issue, can we close this now? If we don't cut it off, it seems this could go on indefinitely.

**Comment by davidkjackson54** [comment]
OK Thanks yes sure it can be closed out. Thanks for the help.
I hope the doc will be completed before too long as it is a good product.

Only then can it be truly considered ready for 'prime time' usage.

**Comment by nexdrew** [comment]
> I hope the doc will be completed before too long as it is a good product.

This is not a product. I'm not selling it. I make $0 off of it. It's an open source library that I created for my own usage, and I give it away for free to anyone who wants to use it.

I understand that there could be more or better docs. I have been upfront and honest about that from the beginning. But I am under no obligation to use my own personal time to write docs for anyone other than myself. If you have ideas for how the docs can be better, please become a contributor and open a pull request.

> Only then can it be truly considered ready for 'prime time' usage.

Do you realize how presumptuous this sounds? I'm not sure what the spirit or intent of this comment was, but please be respectful of my time and efforts.

I have written this library, which makes it very easy to write asynchronous CLI applications, and I offer it for free to anyone. I have written many tests that provide [good test coverage](https://coveralls.io/github/sywac/sywac?branch=master) and contain many examples of how to use the library. I have written a substantial amount of decent documentation. I am happy to answer specific questions about sywac, using my own personal time to provide individual consultation for free. I have given you detailed, formatted, working examples numerous times. I have been patient and willing to help. And, instead of being grateful, you presume to pass judgment on the quality of my work.

I have personally used sywac for many of my projects and scripts, and it works very well. The api is stable and easy to use, the logic has had very few bugs, and the performance is excellent. Without your help, I have already proven that sywac is "ready for 'prime time' usage".

If you don't want to use sywac, you don't have to. But, please, instead of passing judgement, consider giving back to the open source community that has helped you.

**Comment by davidkjackson54** [comment]
It wasn't meant to be taken that way so sorry if it was misconstrued.
Happy to contact you directly in private if that is possible.
