### ISSUE TITLE
sywac and Typescript

### ISSUE THREAD

**Issue by davidkjackson54** [sywac/sywac#28]
Using Typescript. 
Getting a rogue line displayed when showing a help screen after using typescript nd running the resultant JS.
for example:
node cli -h
gives this:

Usage: cli <command> <args> [options]

Commands:
  com   Issue commands
  files     File related functions
  info     System information
  jobs     Job status

str => chalk_1.default.cyan.bold(str)
  (str,

Global Options:
  -h, --help  Show help

The "str =>" line appears in the top level help screen only (and is displayed in bold cyan). The problem doesn't appear to occur in any of the lower level command helps.

I originally had my own styles module mirrored on the doc sample but commented that out but the problem still persists. 
the only item I found close to this  particular text is in the styles module line and states this:
group: str => chalk.cyan.bold(str),

Easy to recreate if required.

![image](https://user-images.githubusercontent.com/46171060/51204016-7440db00-18b7-11e9-9b06-acfcbab62b24.png)

**Comment by davidkjackson54** [comment]
I have tried to narrow this down and have identified the following as being the likely cause and has nothing to do with the use of typescript. 
My top level program - cli.js looks like this:
require('sywac')
  .commandDirectory('commands')
  .showHelpByDefault()
  .help('-h, --help', {
    group: 'Global Options:',
    implicitCommand: false
  })
  .style(require('./style')) // use our own style of colours for help screens
  // .outputSettings({ maxWidth: 63 })
  .parseAndExit() // this initiates parsing of process.argv and will exit the process if any parsing/validation errors occur

Notice the commandDirectory points to the /commands directory
As part of my moving the code over to typescript, I moved my styles.js into the command directory
and changed the line .style require line of code to match. I did that to keep everything sywac related in a common location. - Bad move on my part.

Putting that styles.js into the same directory as pointed to by commandDirectory caused the problem. 
You cannot put anything into the directory pointed to by commandDirectory that is not actually command related.  The result was very weird but in hindsight - not surprising..

**Comment by nexdrew** [comment]
Good to know.

Note this from the [`.commandDirectory(dir, opts)` docs](http://sywac.io/docs/sync-config.html#commandDirectory):

> In order for a command module to be added, it must export one of the following (at least):
>
> 1. An object with a `flags` or `aliases` property (to define command dsl or aliases)
> 2. A function (used as the `run` handler, command alias will be the filename)
>
> Any modules encountered that do not meet these criteria will be ignored.

And this from the [`.style(hooks)` docs](http://sywac.io/docs/sync-config.html#style):

> The following properties are supported:
> 
> - `flags`: function, no default
>    Style the flags for each defined type in generated help text.

Both of them expect the object to declare a `flags` property, meaning that the style module may actually look like a valid command module to sywac.

This is good to point out. Thanks for reporting your findings.
