### ISSUE TITLE
How to specify certain options are required?

### ISSUE THREAD

**Issue by trusktr** [sywac/sywac#47]
I'd like, for example, for two or more specific options to be required, and for that to appear as a detail in the help output in case any of the required options are not present. Is there an API to tell options to be required?

**Comment by trusktr** [comment]
It didn't seem to be documented, but after looking at the code I realized there is a `required` options

Example:

```js
cli
  .string('-o, --one <value>', {
    description: `Option one.`,
    required: true,
  })
  .string('-t, --two <value>', {
    description: `Option two`,
    required: true,
  })
  .version('-v, --version')
  .help('-h, --help')
  .showHelpByDefault()
  .parseAndExit()
  .then(opts => { /* ... your app's logic ... */ })
  .catch(e => {
    console.error(e)
    process.exit(1)
  })
```

And example output when any required option is not set:

```
❯ ./example.js --blah                                                                                                      ✹
Usage: publish [options]

Options:
  -o, --one <value>  Option one.                                                 [required] [string]
  -t, --two <value>  Option two.                                                 [required] [string]
  -v, --version      Show version number                               [commands: version] [boolean]
  -h, --help         Show help                                            [commands: help] [boolean]

Missing required argument: o or one
Missing required argument: t or two
```

**Comment by nexdrew** [comment]
Yes, apologies, there is a lot of documentation that is still lacking.

Yes, the `required` configuration property is for this purpose.

You could also consider using positionals with optional flags, like below. Each positional defined in angle brackets (e.g. `<x>`) is required by default.

```js
require('sywac')
  .positional('[-o|--one] <one-value> [-t|--two] <two-value>', {
    paramsDesc: [
      'Option one',
      'Option two'
    ]
  })
  .version('-v, --version')
  .help('-h, --help')
  .parseAndExit()
```

Does this answer your question? Are we ok to close this issue?

**Comment by nexdrew** [comment]
Closing this for now. Would be happy to revisit if there are any more questions.
