### ISSUE TITLE
How to prevent unknown options

### ISSUE THREAD

**Issue by elliot-nelson** [sywac/sywac#50]
Ideally, I'd like any command line option that is not listed on the usage screen to generate an error.  I don't see any kind of `preventUnknownOptions()` type API after browsing.

Is there a way I could do this today?  I imagine there might be some way to look through the options and find the ones of `UnknownType`, but I don't know how I could do that in a way that would apply globally to all my commands and subcommands.

(As an aside, and a nice-to-have: if this doesn't exist and it's added in the future, it might also be nice to have configurable control over the behavior if the error is triggered, so that I could hook into it and do a git-style `"Unknown option --nmae, did you mean --name?"` error message.)

**Comment by nexdrew** [comment]
@elliot-nelson Thanks for the suggestion!

Sywac doesn't currently have an "easy" way to do this, but I'm beginning to think we should add something to the api. (You're not the first person to ask for this functionality.)

To workaround, you can define a custom [check](http://sywac.io/docs/sync-config.html#check) handler that sniffs out any unknown args and short-circuits when they're found. See #17, especially [my comment here](https://github.com/sywac/sywac/issues/17#issuecomment-392572844).

**Comment by nexdrew** [comment]
Released PR #51 as [v1.3.0](https://github.com/sywac/sywac/releases/tag/v1.3.0) on [npm](https://www.npmjs.com/package/sywac).

We haven't yet addressed the nice-to-have feature you mentioned in the issue description, but we at least now have `.strict()` mode available.

Give it a spin and let me know what you think. Thanks for all your help so far!
