### ISSUE TITLE
Default commands with positional args behave unexpectedly

### ISSUE THREAD

**Issue by elliot-nelson** [sywac/sywac#59]
An example program:

```js
require('sywac')
    .command('kiss <player>', argv => console.log(`You kissed ${argv.player}`))
    .command('attack <player>', argv => console.log(`You attacked ${argv.player}`))
    .command('* <player>', argv => console.log(`You tried to ${argv._[0]} ${argv.player}`))
    .parseAndExit()
```

```console
$ ./example kiss Susan
You kissed Susan

$ ./example attack Brenda
You attacked Brenda

$ ./example examine Dave
You tried to Dave examine
```

The issue, I think, is that when we begin parsing for the implicitly matched default command, `_` contains `['examine', 'Dave']`.  We then process all positional args from the DSL, mistakenly applying the _first_ (`examine`) to `player`, leaving `Dave` sitting in `_`.

Filing as a bug because I think it's clearly wrong for `argv.player` to be `examine` in this situation, but I'm not sure on the right solution.  We could _slurp_ `examine` into `argv['*']` and the problem would go away, but that might cause other issues (it would totally prevent two nested implicit commands, for one thing).

**Comment by nexdrew** [comment]
I'm not entirely sure a default command _without a non-default alias_ and _with positional args_ makes sense.

For one thing, a default command that has no non-default alias will be hidden from help text, so, in your example, how would the user know (or why would they expect) that `examine Dave` would be a valid command? It seems invalid to me.

For this use-case, I would recommend one of two approaches:

1. Define an `examine <player>` command that is also considered default via `aliases: '*'`, like so:

    ```js
    require('sywac')
      .command('kiss <player>', argv => console.log(`You kissed ${argv.player}`))
      .command('attack <player>', argv => console.log(`You attacked ${argv.player}`))
      .command('examine <player>', {
        aliases: '*',
        run: argv => console.log(`You tried to examine ${argv.player}`)
      })
      .help('-h').outputSettings({ maxWidth: 41 })
      .parseAndExit()
    ```

    ```console
    $ node issue59.js -h
    Usage: issue59 <command> <args> [options]

    Commands:
      kiss <player>   
      attack <player> 
      examine <player>              [default]

    Options:
      -h  Show help                 [boolean]
    ```

    ```console
    $ node issue59.js examine Dave
    You tried to examine Dave
    ```

    ```console
    $ node issue59.js Dave
    You tried to examine Dave
    ```

2. Define a (hidden) default command that relies on `argv._` instead of positionals

    ```js
    require('sywac')
      .command('kiss <player>', argv => console.log(`You kissed ${argv.player}`))
      .command('attack <player>', argv => console.log(`You attacked ${argv.player}`))
      .command('*', (argv, ctx) => {
        if (!argv._.length) return ctx.cliMessage('Please specify a command and/or player name')
        console.log(`You didn't specify a command so we'll try to examine ${argv._[0]}`)
      })
      .help('-h').outputSettings({ maxWidth: 41 })
      .parseAndExit()
    ```

    ```console
    $ node issue59.js -h
    Usage: issue59 <command> <args> [options]

    Commands:
      kiss <player>  
      attack <player>

    Options:
      -h  Show help                 [boolean]
    ```

    ```console
    $ node issue59.js
    Usage: issue59 <command> <args> [options]

    Commands:
      kiss <player>  
      attack <player>

    Options:
      -h  Show help                 [boolean]

    Please specify a command and/or player name
    ```

    ```console
    $ node issue59.js Dave
    You didn't specify a command so we'll try to examine Dave
    ```

Only in the first example does the user have any way of knowing that `examine Dave` is a valid command.

In my opinion, the primary use-case for default commands is to run something when no args are expected/given.

I think your example is a different use-case that doesn't align well with default commands.

For these reasons, I think the odd behavior you describe is not really a bug, since expected behavior of a hidden default command that expects positional args is somewhat undefined and is not a use-case supported by sywac.

Happy to hear your thoughts on the matter.

**Comment by nexdrew** [comment]
Another possible alternative is to define your default command as `* <action> <player`, such that (a) two non-command positional arguments are required and (b) `argv.action` and `argv.player` are populated from the first two positionals, but I still don't think this is an optimal choice.

```js
require('sywac')
  .command('kiss <player>', argv => console.log(`You kissed ${argv.player}`))
  .command('attack <player>', argv => console.log(`You attacked ${argv.player}`))
  .command('* <action> <player>', argv => console.log(`You tried to ${argv.action} ${argv.player}`))
  .help('-h').outputSettings({ maxWidth: 41 })
  .parseAndExit()
```

This may give you, as the CLI author, behavior that is more expected than `* <player>`, but I think it still makes an awkward CLI experience for the user.

The default command is still not included in help text by default:

```console
$ node issue59.js -h
Usage: issue59 <command> <args> [options]

Commands:
  kiss <player>  
  attack <player>

Options:
  -h  Show help                 [boolean]
```

This works:

```console
$ node issue59.js examine Dave
You tried to examine Dave
```

But running the program without at least two args gives the user odd help text:

```console
$ node issue59.js
Usage: issue59 * <action> <player> [options]

Arguments:
  <action>            [required] [string]
  <player>            [required] [string]

Options:
  -h  Show help                 [boolean]

Missing required argument: action
Missing required argument: player
```

```console
$ node issue59.js chat
Usage: issue59 * <action> <player> [options]

Arguments:
  <action>            [required] [string]
  <player>            [required] [string]

Options:
  -h  Show help                 [boolean]

Missing required argument: player
```

**Comment by elliot-nelson** [comment]
Lots of options, thanks for those details!

Is there any way to do Option #1 using single-arg `.command`?  I usually do commands using blocks so that I can split them into multiple files, like `.command(require('./subcommand'))`.  But using that method, I can provide the `aliases` key but there's no separate `dsl` key: I'm not sure how to do `examine <player>` with an alias of `*` using a command module.

**Comment by nexdrew** [comment]
@elliot-nelson Yeah, you have to use the `flags` property for the DSL string. I used `flags` instead of `dsl` to try to maintain consistency with other (non-command) types.

So you can either use a plain ol' object:

```js
sywac.command({
  flags: 'examine <player>',
  aliases: '*', // or ['*']
  run: argv => console.log(`You tried to examine ${argv.player}`)
})
```

Or you can use a fancy class:

```js
class ExamineCommand {
  constructor () {
    this.flags = 'examine <player>'
    this.aliases = '*' // or ['*']
    this.run = this.run.bind(this)
  }

  run (argv) {
    console.log(`You tried to examine ${argv.player}`)
  }
}

sywac.command(new ExamineCommand())
```

Hope this helps!

**Comment by elliot-nelson** [comment]
Ahhh... thanks for that!  I think for now nothing needs to change, but I'll make some notes for future Tips in the command documentation.

**Comment by nexdrew** [comment]
Sounds good. Thanks!
