### ISSUE TITLE
Prep for Hacktoberfest

### ISSUE THREAD

**Issue by elliot-nelson** [sywac/sywac#73]
If we can come up with a list of relatively easy features on the roadmap that first-time contributors could tackle successfully, and aren't just busy work, it would be nice to throw them up for Hacktoberfest this year.

Ideally we can get them written up (or just apply a little polish if they are already written) in mid-late September, then we'd be ready to slap on the label at beginning of October.  Free labor and exposure for sywac, useful and interesting work to do for OSS developers (and potentially new fans of sywac afterwards!).

**Comment by nexdrew** [comment]
@elliot-nelson Great idea!

Unfortunately, I don't know if any of the current issues (or anything on my original roadmap) would be good candidates for new-comers.

Here's a brief list:
- Current issues
  - Help with documentation (related to #11)
  - Ability to customize "text wrapping" via style hook (#57)
  - Support functions (needs an interface) for synchronous config options (#62)
  - Top-level run handler (#65)
  - Ability to customize the "end of options" delimiter (#67)
  - Config option to support auto-conversion of kebab-case flags to camelCase (#68)
  - Ability to document and style exit codes in help text (#69)
  - TypeScript typings definition (#70)
  - Better support for implicit commands - simple commands kicked off via boolean flag (#71)
- Things from ["The Roadmap"](https://sywac.io/about/roadmap.html)
  - Ability to read arguments from stdin
  - Ability to parse environment variables as arguments/options
  - Add `--no-` negation support to `TypeBoolean`
  - Interactive mode (!)

Maybe we could go down this list and assign t-shirt size labels (small, medium, large) to them based on the amount of effort (or familiarity with existing codebase) we think will be required?

Shooting from the hip, the potential candidates that stand out to me are #11, #67, and _maybe_ #68, #69, and #70.

What do you think?

**Comment by elliot-nelson** [comment]
Great summary!

I agree that not everything is a good fit, but I'll make my case for a few:

1. "Adding --no negation for TypeBoolean".  I think this feature is low-complexity and relatively easy to test, and makes sense to anyone with any CLI experience (no sywac expertise required).  This could probably be a small t-shirt Hacktoberfest ticket.

2. "Customized extra args delimiter" (#67).  Agree on this one, also low-complexity and relatively easy to test, small t-shirt?

3. "Document exit codes in help text" (#69).  I'd call this a medium t-shirt because it will probably require a draft PR, some back and forth on exactly how it should be styled (and any new style names if required), and then some polishing up.  But easily doable within October if someone interested came along, even if they were unfamiliar with sywac.

4. TypeScript (#70).  Yeah this is a reality today for library authors and an open call during Hacktoberfest could make a lot of sense for attracting TS experts.  I think we would want to make some decisions about exactly what we want and write that up -- your usual options are: A. completely convert your library to TS; B. include TS bindings inside your own library and maintain them as you make JS changes; C. host types in DefinitelyTyped aka @types; D. do nothing, in order of dedication.  Depending on whether we're putting a call out for B. or C., and how much of Jose's existing work we can reuse, may affect whether this is a medium or large t-shirt.

Those are the ones that stick out to me!  Some of the others (like documentation) are nice to haves but it's tough to have someone who's never used a library write documentation for it.

**Comment by elliot-nelson** [comment]
I'm closing this feature (although it's still very useful as a reference).

Our "Hacktoberfest offering" for this year is several labeled issues under `sywac` and `sywac-website`, and a couple of pinned welcome issues.  I think that's a good starting point to see if there is any interest from the community.
